name: C++ CI Build and Boot Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx for better build performance
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      # Build the Docker container
      - name: Build Docker image
        run: |
          docker build --tag cpp-dev-container .

      # Run the boot test: Check if the container starts correctly and runs the tests
      - name: Run Boot Test
        run: |
          docker run --rm cpp-dev-container ctest --output-on-failure

      # Optionally push the Docker image to DockerHub (if needed)
      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker tag cpp-dev-container ${{ secrets.DOCKER_USERNAME }}/cpp-dev-container:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cpp-dev-container:latest
